/**
 * Items Server Actions
 *
 * SECURITY:
 * - All mutations verify admin role server-side
 * - Input validated with Zod
 * - SKU generated by DB sequence, not from client
 * - Barcode validated for format and uniqueness
 */
'use server'

import { createSupabaseServerClient } from '@/lib/supabase/server'
import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { validateBarcodeFormat, generateAutoBarcodePattern } from '@/lib/validation/barcode'
import { createAuditLog } from '@/lib/audit'

const barcodeFormatValues = ['EAN13', 'EAN8', 'UPCA', 'UPCE', 'CODE128', 'QR'] as const

export interface GenerateBarcodeResult {
  success: boolean
  barcode?: string
  error?: string
}

/**
 * Generate a unique auto barcode (IB-XXXXXX) for Code 128 format.
 * Checks DB for collisions and retries up to 10 attempts.
 * SECURITY: Server-side check only; does NOT mutate or insert into database.
 */
export async function generateAutoBarcode(): Promise<GenerateBarcodeResult> {
  try {
    const { supabase, isAdmin } = await verifyAdmin()
    if (!isAdmin) {
      return { success: false, error: 'Akses ditolak.' }
    }

    const MAX_ATTEMPTS = 10
    for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
      const code = generateAutoBarcodePattern()

      const { data: existing, error } = await supabase
        .from('items')
        .select('id')
        .eq('barcode', code)
        .limit(1)

      if (error) {
        return { success: false, error: 'Gagal memeriksa keunikan barcode di database.' }
      }

      if (!existing || existing.length === 0) {
        return { success: true, barcode: code }
      }
    }

    return {
      success: false,
      error: 'Gagal membuat barcode unik setelah beberapa percobaan. Silakan coba lagi.',
    }
  } catch {
    return { success: false, error: 'Terjadi kesalahan pada server saat membuat barcode.' }
  }
}

const itemCreateSchema = z.object({
  name: z.string().min(1, 'Nama barang wajib diisi.').max(200, 'Nama barang maksimal 200 karakter.').trim(),
  category_id: z.string().uuid('Kategori tidak valid.'),
  base_unit_id: z.string().uuid('Satuan dasar tidak valid.'),
  barcode: z
    .string()
    .min(1, 'Barcode wajib diisi.')
    .max(256, 'Barcode maksimal 256 karakter.')
    .transform((v) => v.trim()),
  barcode_format: z.enum(barcodeFormatValues, { message: 'Format barcode tidak valid.' }),
  minimum_stock: z
    .string()
    .regex(/^\d+$/, 'Batas minimum harus bilangan bulat non-negatif.')
    .transform((v) => parseInt(v, 10)),
  notes: z.string().max(500, 'Keterangan maksimal 500 karakter.').trim().optional(),
})

const itemUpdateSchema = z.object({
  name: z.string().min(1, 'Nama barang wajib diisi.').max(200).trim().optional(),
  category_id: z.string().uuid().optional(),
  barcode: z.string().min(1).max(256).transform((v) => v.trim()).optional(),
  barcode_format: z.enum(barcodeFormatValues).optional(),
  minimum_stock: z
    .string()
    .regex(/^\d+$/, 'Batas minimum harus bilangan bulat non-negatif.')
    .transform((v) => parseInt(v, 10))
    .optional(),
  notes: z.string().max(500).trim().optional(),
})

export interface ActionResult {
  success: boolean
  error?: string
  data?: { id?: string; sku?: string }
}

async function verifyAdmin() {
  const supabase = await createSupabaseServerClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { supabase, isAdmin: false, user: null }

  const { data: profile } = await supabase
    .from('profiles')
    .select('role,is_active')
    .eq('id', user.id)
    .single()

  return {
    supabase,
    isAdmin: !!(profile?.is_active && profile.role === 'ADMIN'),
    user,
  }
}

/**
 * Create a new item (admin only)
 * SKU auto-generated by database sequence
 */
export async function createItem(formData: FormData): Promise<ActionResult> {
  try {
    const { supabase, isAdmin } = await verifyAdmin()
    if (!isAdmin) return { success: false, error: 'Akses ditolak.' }

    const rawData = {
      name: formData.get('name') as string,
      category_id: formData.get('category_id') as string,
      base_unit_id: formData.get('base_unit_id') as string,
      barcode: formData.get('barcode') as string,
      barcode_format: formData.get('barcode_format') as string,
      minimum_stock: formData.get('minimum_stock') as string,
      notes: (formData.get('notes') as string) || undefined,
    }

    const parsed = itemCreateSchema.safeParse(rawData)
    if (!parsed.success) {
      return {
        success: false,
        error: parsed.error.issues.map((i) => i.message).join(' '),
      }
    }

    const barcodeValid = validateBarcodeFormat(parsed.data.barcode, parsed.data.barcode_format)
    if (!barcodeValid.valid) {
      return { success: false, error: barcodeValid.error ?? 'Barcode tidak valid.' }
    }

    const customSku = (formData.get('sku') as string)?.trim() || null
    if (customSku && !/^ATK-\d{4,}$/.test(customSku)) {
      return { success: false, error: 'Format SKU harus ATK- diikuti minimal 4 digit.' }
    }

    const insertData = {
      ...(customSku ? { sku: customSku } : {}),
      name: parsed.data.name,
      category_id: parsed.data.category_id,
      base_unit_id: parsed.data.base_unit_id,
      default_purchase_unit_id: parsed.data.base_unit_id,
      barcode: parsed.data.barcode,
      barcode_format: parsed.data.barcode_format,
      minimum_stock: parsed.data.minimum_stock,
      notes: parsed.data.notes ?? null,
      is_active: true,
    }

    const { data: item, error } = await supabase.from('items').insert(insertData).select('id,sku').single()

    if (error) {
      if (error.code === '23505') {
        if (error.message.includes('barcode')) {
          return { success: false, error: 'Barcode tersebut sudah digunakan oleh barang lain.' }
        }
        if (error.message.includes('sku')) {
          return { success: false, error: 'SKU tersebut sudah ada.' }
        }
        return { success: false, error: 'Data duplikat.' }
      }
      return { success: false, error: 'Gagal membuat barang.' }
    }

    await createAuditLog(supabase, {
      action: 'ITEM_CREATED',
      entity_type: 'items',
      entity_id: item?.id ?? null,
      changes_summary: { name: parsed.data.name, sku: item?.sku, barcode: parsed.data.barcode },
    })

    revalidatePath('/admin/items')
    return { success: true, data: { id: item?.id, sku: item?.sku } }
  } catch (e) {
    return { success: false, error: e instanceof Error ? e.message : 'Terjadi kesalahan pada server.' }
  }
}

/**
 * Update item descriptive data (admin only)
 * Cannot change: SKU, base_unit after transactions exist
 */
export async function updateItem(id: string, formData: FormData): Promise<ActionResult> {
  try {
    const { supabase, isAdmin } = await verifyAdmin()
    if (!isAdmin) return { success: false, error: 'Akses ditolak.' }

    const rawData = {
      name: (formData.get('name') as string) || undefined,
      category_id: (formData.get('category_id') as string) || undefined,
      barcode: (formData.get('barcode') as string) || undefined,
      barcode_format: (formData.get('barcode_format') as string) || undefined,
      minimum_stock: (formData.get('minimum_stock') as string) || undefined,
      notes: (formData.get('notes') as string) || undefined,
    }

    const parsed = itemUpdateSchema.safeParse(rawData)
    if (!parsed.success) {
      return { success: false, error: parsed.error.issues.map((i) => i.message).join(' ') }
    }

    if (parsed.data.barcode && parsed.data.barcode_format) {
      const barcodeValid = validateBarcodeFormat(parsed.data.barcode, parsed.data.barcode_format)
      if (!barcodeValid.valid) {
        return { success: false, error: barcodeValid.error ?? 'Barcode tidak valid.' }
      }
    }

    const { error } = await supabase
      .from('items')
      .update({
        ...(parsed.data.name ? { name: parsed.data.name } : {}),
        ...(parsed.data.category_id ? { category_id: parsed.data.category_id } : {}),
        ...(parsed.data.barcode ? { barcode: parsed.data.barcode } : {}),
        ...(parsed.data.barcode_format ? { barcode_format: parsed.data.barcode_format } : {}),
        ...(parsed.data.minimum_stock !== undefined ? { minimum_stock: parsed.data.minimum_stock } : {}),
        ...(parsed.data.notes !== undefined ? { notes: parsed.data.notes || null } : {}),
      })
      .eq('id', id)

    if (error) {
      if (error.code === '23505') {
        return { success: false, error: 'Barcode tersebut sudah digunakan oleh barang lain.' }
      }
      return { success: false, error: 'Gagal memperbarui barang.' }
    }

    await createAuditLog(supabase, {
      action: 'ITEM_UPDATED',
      entity_type: 'items',
      entity_id: id,
      changes_summary: { ...parsed.data },
    })

    revalidatePath('/admin/items')
    revalidatePath(`/admin/items/${id}`)
    return { success: true }
  } catch (e) {
    return { success: false, error: e instanceof Error ? e.message : 'Terjadi kesalahan pada server.' }
  }
}

/**
 * Deactivate an item (admin only)
 * Allowed for any item regardless of stock or transaction history.
 * Atomic: status update & audit log occur in a single database RPC transaction.
 */
export async function deactivateItem(id: string): Promise<ActionResult> {
  try {
    const { supabase, isAdmin } = await verifyAdmin()
    if (!isAdmin) return { success: false, error: 'Akses ditolak.' }

    const { error } = await supabase.rpc('toggle_item_active', {
      p_item_id: id,
      p_target_is_active: false,
    })

    if (error) {
      if (error.message.includes('ITEM_ALREADY_INACTIVE')) {
        return { success: false, error: 'Barang sudah nonaktif.' }
      }
      if (error.message.includes('ITEM_NOT_FOUND')) {
        return { success: false, error: 'Barang tidak ditemukan.' }
      }
      return { success: false, error: `Gagal menonaktifkan barang: ${error.message}` }
    }

    revalidatePath('/admin/items')
    revalidatePath(`/admin/items/${id}`)
    return { success: true }
  } catch (e) {
    return { success: false, error: e instanceof Error ? e.message : 'Terjadi kesalahan pada server.' }
  }
}

/**
 * Reactivate an item (admin only)
 * Atomic: status update & audit log occur in a single database RPC transaction.
 */
export async function activateItem(id: string): Promise<ActionResult> {
  try {
    const { supabase, isAdmin } = await verifyAdmin()
    if (!isAdmin) return { success: false, error: 'Akses ditolak.' }

    const { error } = await supabase.rpc('toggle_item_active', {
      p_item_id: id,
      p_target_is_active: true,
    })

    if (error) {
      if (error.message.includes('ITEM_ALREADY_ACTIVE')) {
        return { success: false, error: 'Barang sudah aktif.' }
      }
      if (error.message.includes('ITEM_NOT_FOUND')) {
        return { success: false, error: 'Barang tidak ditemukan.' }
      }
      return { success: false, error: `Gagal mengaktifkan barang: ${error.message}` }
    }

    revalidatePath('/admin/items')
    revalidatePath(`/admin/items/${id}`)
    return { success: true }
  } catch (e) {
    return { success: false, error: e instanceof Error ? e.message : 'Terjadi kesalahan pada server.' }
  }
}
